// ladder_to_ld_converter.cpp
// Copyright 2024 PLC Emulator Project
//
// Implementation of LD converter.

#include "plc_emulator/project/ladder_to_ld_converter.h"

#include "plc_emulator/programming/programming_mode.h"  // 🔥 **IMPORTANT**: 실제 타입 정의 포함
#include "plc_emulator/project/ladder_ir.h"  // 🔥 **NEW**: LadderIR 지원

#include <algorithm>
#include <iomanip>  // 🔥 **NEW**: setw 지원
#include <iostream>
#include <set>
#include <sstream>

namespace plc {

LadderToLDConverter::LadderToLDConverter() {
  debug_mode_ = false;
}

LadderToLDConverter::~LadderToLDConverter() {}

bool LadderToLDConverter::ConvertToLDFile(const LadderProgram& program,
                                          const std::string& outputPath) {
  std::string ldContent = ConvertToLDString(program);

  if (ldContent.empty()) {
    last_error_ = "Failed to convert ladder program to LD format";
    return false;
  }

  std::ofstream file(outputPath);
  if (!file.is_open()) {
    last_error_ = "Cannot open output file: " + outputPath;
    return false;
  }

  file << ldContent;
  file.close();

  DebugLog("Successfully saved .ld file to: " + outputPath);
  return true;
}

std::string LadderToLDConverter::ConvertToLDString(
    const LadderProgram& program) {
  last_error_.clear();

  std::string ldContent;

  // 1. .ld 파일 헤더 생성
  ldContent += GenerateLDHeader();
  ldContent += "\n";

  // 2. OR 블록 그룹 분석
  std::vector<ORGroup> orGroups = AnalyzeORGroups(program);
  std::set<int> processedRungs;

  DebugLog("Found " + std::to_string(orGroups.size()) + " OR groups");

  // 3. OR 블록들을 변환
  for (const auto& group : orGroups) {
    DebugLog("Converting OR group with " +
             std::to_string(group.rungIndices.size()) + " rungs");

    ldContent += "(* OR Block Group *)\n";
    ldContent += "LD ";

    bool firstRung = true;
    for (int rungIndex : group.rungIndices) {
      if (rungIndex >= 0 &&
          rungIndex < static_cast<int>(program.rungs.size())) {
        const auto& rung = program.rungs[rungIndex];

        if (!firstRung) {
          ldContent += "\nOR ";
        } else {
          firstRung = false;
        }

        // rung의 조건 부분만 변환 (출력 제외)
        bool hasCondition = false;
        for (const auto& cell : rung.cells) {
          if (cell.type == LadderInstructionType::XIC ||
              cell.type == LadderInstructionType::XIO) {
            if (hasCondition) {
              ldContent += "\nAND ";
            }

            if (cell.type == LadderInstructionType::XIO) {
              ldContent += "NOT ";
            }

            ldContent += ConvertAddress(cell.address);
            hasCondition = true;
          } else if (cell.type == LadderInstructionType::OTE ||
                     cell.type == LadderInstructionType::SET ||
                     cell.type == LadderInstructionType::RST) {
            break;  // 출력 명령어는 제외
          }
        }

        processedRungs.insert(rungIndex);
      }
    }

    // 출력 명령어
    if (!group.outputAddress.empty()) {
      ldContent += "\nST " + ConvertAddress(group.outputAddress) + "\n\n";
    }
  }

  // 4. 독립적인 rung들 변환
  for (size_t i = 0; i < program.rungs.size(); ++i) {
    if (program.rungs[i].isEndRung)
      break;

    if (processedRungs.find(i) == processedRungs.end()) {
      DebugLog("Converting independent rung " + std::to_string(i));
      ConvertSingleRung(program.rungs[i], i, ldContent);
    }
  }

  // 5. .ld 파일 푸터
  ldContent += "\n(* End of Program *)\n";
  ldContent += "END_PROGRAM\n";

  return ldContent;
}

std::string LadderToLDConverter::GenerateLDHeader() {
  std::string header;

  header += "(* Generated by FX3U PLC Simulator *)\n";
  header += "(* Compatible with OpenPLC Runtime *)\n";
  header += "\n";
  header += "PROGRAM PLC_PRG\n";
  header += "VAR\n";

  // FX3U-32M I/O 변수 선언
  header += "  (* Input Variables X0-X15 *)\n";
  for (int i = 0; i < 16; i++) {
    header += "  X" + std::to_string(i) + " AT %IX0." + std::to_string(i) +
              " : BOOL;\n";
  }

  header += "\n  (* Output Variables Y0-Y15 *)\n";
  for (int i = 0; i < 16; i++) {
    header += "  Y" + std::to_string(i) + " AT %QX0." + std::to_string(i) +
              " : BOOL;\n";
  }

  header += "\n  (* Internal Memory M0-M999 *)\n";
  for (int i = 0; i < 1000; i++) {
    header += "  M" + std::to_string(i) + " : BOOL;\n";
  }

  header += "END_VAR\n\n";

  return header;
}

std::vector<LadderToLDConverter::ORGroup> LadderToLDConverter::AnalyzeORGroups(
    const LadderProgram& program) {
  std::vector<ORGroup> groups;

  for (const auto& connection : program.verticalConnections) {
    ORGroup group;
    group.rungIndices = connection.rungs;
    group.outputColumn = 11;  // 기본 출력 위치

    // 연결된 rung들에서 출력 주소 찾기
    for (int rungIndex : connection.rungs) {
      if (rungIndex >= 0 &&
          rungIndex < static_cast<int>(program.rungs.size())) {
        const auto& rung = program.rungs[rungIndex];

        for (const auto& cell : rung.cells) {
          if (cell.type == LadderInstructionType::OTE ||
              cell.type == LadderInstructionType::SET ||
              cell.type == LadderInstructionType::RST) {
            if (!cell.address.empty()) {
              group.outputAddress = cell.address;
              break;
            }
          }
        }

        if (!group.outputAddress.empty()) {
          break;
        }
      }
    }

    if (!group.rungIndices.empty()) {
      groups.push_back(group);
    }
  }

  return groups;
}

void LadderToLDConverter::ConvertSingleRung(const Rung& rung, int rungIndex,
                                            std::string& ldContent) {
  ldContent += "(* Rung " + std::to_string(rungIndex) + " *)\n";

  bool hasCondition = false;
  bool firstCondition = true;
  std::string outputAddress;
  LadderInstructionType outputType = LadderInstructionType::EMPTY;

  // 조건 부분 처리
  for (const auto& cell : rung.cells) {
    if (cell.type == LadderInstructionType::XIC ||
        cell.type == LadderInstructionType::XIO) {
      if (firstCondition) {
        ldContent += "LD ";
        firstCondition = false;
      } else {
        ldContent += "\nAND ";
      }

      if (cell.type == LadderInstructionType::XIO) {
        ldContent += "NOT ";
      }

      ldContent += ConvertAddress(cell.address);
      hasCondition = true;
    } else if (cell.type == LadderInstructionType::OTE ||
               cell.type == LadderInstructionType::SET ||
               cell.type == LadderInstructionType::RST) {
      outputAddress = cell.address;
      outputType = cell.type;
      break;
    }
  }

  // 출력 부분 처리
  if (!outputAddress.empty()) {
    if (!hasCondition) {
      ldContent += "LD TRUE";  // 조건이 없으면 항상 참
    }

    if (outputType == LadderInstructionType::SET) {
      ldContent += "\nS " + ConvertAddress(outputAddress);
    } else if (outputType == LadderInstructionType::RST) {
      ldContent += "\nR " + ConvertAddress(outputAddress);
    } else {
      ldContent += "\nST " + ConvertAddress(outputAddress);
    }
  }

  ldContent += "\n\n";
}

std::string LadderToLDConverter::ConvertAddress(const std::string& address) {
  if (address.empty())
    return "";

  char deviceType = address[0];
  int deviceNumber = 0;

  try {
    deviceNumber = std::stoi(address.substr(1));
  } catch (...) {
    return address;  // 변환 실패 시 원래 주소 반환
  }

  switch (deviceType) {
    case 'X':
      if (deviceNumber >= 0 && deviceNumber <= 15) {
        return "X" + std::to_string(deviceNumber);
      }
      break;
    case 'Y':
      if (deviceNumber >= 0 && deviceNumber <= 15) {
        return "Y" + std::to_string(deviceNumber);
      }
      break;
    case 'M':
      if (deviceNumber >= 0 && deviceNumber <= 999) {
        return "M" + std::to_string(deviceNumber);
      }
      break;
  }

  return address;  // 변환할 수 없는 주소는 그대로 반환
}

std::string LadderToLDConverter::GetLDInstructionName(
    LadderInstructionType type) {
  switch (type) {
    case LadderInstructionType::XIC:
      return "LD";
    case LadderInstructionType::XIO:
      return "LDN";
    case LadderInstructionType::OTE:
      return "ST";
    case LadderInstructionType::SET:
      return "S";
    case LadderInstructionType::RST:
      return "R";
    case LadderInstructionType::TON:
      return "TON";
    case LadderInstructionType::CTU:
      return "CTU";
    default:
      return "";
  }
}

void LadderToLDConverter::DebugLog(const std::string& message) {
  if (debug_mode_) {
    std::cout << "[LadderToLDConverter] " << message << std::endl;
  }
}

// ============================================================================
// 🔥 **NEW**: IR 기반 고정밀도 변환 함수들 (Phase 3)
// ============================================================================

std::string LadderToLDConverter::ConvertToLDStringWithIR(
    const LadderProgram& program) {
  DebugLog("🔥 Starting IR-based conversion...");
  last_error_.clear();

  // 1. LadderProgram → LadderIR 변환
  DebugLog("Step 1: Converting to IR...");
  LadderIRProgram irProgram = LadderToIRConverter::ConvertToIR(program);

  // IR 구조 디버그 출력
  if (debug_mode_) {
    irProgram.PrintIRStructure();
  }

  // 2. LadderIR → 스택 명령어 변환
  DebugLog("Step 2: Generating stack instructions...");
  std::vector<std::string> stackInstructions =
      GenerateStackInstructions(irProgram);

  // 3. .ld 파일 형식으로 조합
  DebugLog("Step 3: Building .ld file content...");
  std::stringstream ldContent;

  // .ld 파일 헤더
  ldContent << GenerateLDHeader() << "\n\n";

  // 메인 PROGRAM 섹션
  ldContent << "PROGRAM main\n";
  ldContent << "VAR\n";
  ldContent << "END_VAR\n\n";

  // 스택 명령어들을 .ld 형식으로 변환
  for (const auto& instruction : stackInstructions) {
    if (!instruction.empty()) {
      ldContent << "    " << instruction << ";\n";
    }
  }

  ldContent << "\nEND_PROGRAM\n";

  DebugLog("✅ IR-based conversion completed successfully!");
  return ldContent.str();
}

std::vector<std::string> LadderToLDConverter::GenerateStackInstructions(
    const LadderIRProgram& irProgram) {
  DebugLog(
      "Generating advanced stack instructions with MPS/ORB/MPP support...");

  // IR → 스택 명령어 변환 (고급 병렬 처리 포함)
  std::vector<std::string> instructions =
      IRToStackConverter::ConvertToStackInstructions(irProgram);

  // 📊 **변환 통계 로깅**
  DebugLog("Generated " + std::to_string(instructions.size()) +
           " stack instructions");

  if (debug_mode_) {
    std::cout << "\n=== Generated Stack Instructions ===\n";
    for (size_t i = 0; i < instructions.size(); ++i) {
      std::cout << std::setw(3) << i + 1 << ": " << instructions[i] << "\n";
    }
    std::cout << "=====================================\n\n";
  }

  // 🧠 **추론**: 스택 명령어 후처리
  // OpenPLC는 특정 형식을 요구하므로 명령어 형식 조정
  for (auto& instruction : instructions) {
    // LOAD → LD 변환
    if (instruction.find("LOAD ") == 0) {
      instruction.replace(0, 5, "LD ");
    }
    // LOAD_NOT → LDN 변환
    else if (instruction.find("LOAD_NOT ") == 0) {
      instruction.replace(0, 9, "LDN ");
    }
    // OUT → ST 변환
    else if (instruction.find("OUT ") == 0) {
      instruction.replace(0, 4, "ST ");
    }
    // AND_NOT → ANDN 변환
    else if (instruction.find("AND_NOT ") == 0) {
      instruction.replace(0, 8, "ANDN ");
    }
    // OR_NOT → ORN 변환
    else if (instruction.find("OR_NOT ") == 0) {
      instruction.replace(0, 7, "ORN ");
    }
  }

  DebugLog("Stack instruction post-processing completed");
  return instructions;
}

}  // namespace plc